apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: product-catalog
spec:
  replicas: 2 # Start with 2 replicas for basic availability
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-docker-repo/product-catalog-backend:latest # IMPORTANT: Replace with your actual image path
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql-service" # The name of the MySQL service
            - name: DB_USER
              value: "app_user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              value: "product_catalog"
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: product-catalog
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
