apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: product-catalog
spec:
  replicas: 2 # Start with 2 replicas for basic availability
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-docker-repo/product-catalog-frontend:latest # IMPORTANT: Replace with your actual image path
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: product-catalog
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
