apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: product-catalog
type: Opaque
data:
  # These values should be base64 encoded.
  # echo -n 'your_strong_root_password' | base64
  # echo -n 'your_strong_password' | base64
  MYSQL_ROOT_PASSWORD: eW91cl9zdHJvbmdfcm9vdF9wYXNzd29yZA==
  MYSQL_PASSWORD: eW91cl9zdHJvbmdfcGFzc3dvcmQ=

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: product-catalog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request 1 GiB of storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          command: ["--default-authentication-plugin=mysql_native_password"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "product_catalog"
            - name: MYSQL_USER
              value: "app_user"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name's: init-db
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-db
          configMap:
            name: mysql-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: product-catalog
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
